# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import table_pb2 as table__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in table_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TableStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ColSum = channel.unary_unary(
                '/Table/ColSum',
                request_serializer=table__pb2.ColSumReq.SerializeToString,
                response_deserializer=table__pb2.ColSumResp.FromString,
                _registered_method=True)
        self.Upload = channel.unary_unary(
                '/Table/Upload',
                request_serializer=table__pb2.UploadReq.SerializeToString,
                response_deserializer=table__pb2.UploadResp.FromString,
                _registered_method=True)


class TableServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ColSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ColSum': grpc.unary_unary_rpc_method_handler(
                    servicer.ColSum,
                    request_deserializer=table__pb2.ColSumReq.FromString,
                    response_serializer=table__pb2.ColSumResp.SerializeToString,
            ),
            'Upload': grpc.unary_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=table__pb2.UploadReq.FromString,
                    response_serializer=table__pb2.UploadResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Table', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Table', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Table(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ColSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Table/ColSum',
            table__pb2.ColSumReq.SerializeToString,
            table__pb2.ColSumResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Table/Upload',
            table__pb2.UploadReq.SerializeToString,
            table__pb2.UploadResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
